"""Measure existing transparent bar apertures; no artwork is changed.

Emits scanline geometry rather than an inset rectangle, preserving rounded ends
and ornaments intruding into the fill. Flash Bang Guy is deliberately excluded.
"""
from pathlib import Path
from PIL import Image
import numpy as np
import json
from collections import deque

root=Path(__file__).resolve().parents[1]
result=[]
header=['// Generated by Tools/measure_boss_health_windows.py. Do not hand-edit.',
        '#pragma once','namespace BossHealthWindows {',
        'struct FSpan { int Y, Height, Left, Right; };',
        'struct FWindow { int Width, Height, Left, Right; const FSpan* Spans; int Count; };']
for i in range(6):
    image=Image.open(root/f'Content/Art/September/BossBorder_{i}.png').convert('RGBA')
    alpha=np.array(image)[:,:,3];h,w=alpha.shape;cx=w//2
    # Pick the central long clear run, not transparent space outside the frame.
    ys=np.flatnonzero(alpha[:,cx]==0);runs=np.split(ys,np.where(np.diff(ys)>1)[0]+1)
    candidates=[r for r in runs if len(r)>10 and r[0]>h*.25 and r[-1]<h*.8]
    rows=min(candidates,key=lambda r:abs(float(r.mean())-h*.52))
    mask=np.zeros_like(alpha,dtype=bool);seed=(int(rows[len(rows)//2]),cx)
    pending=deque([seed]);mask[seed]=True
    while pending:
        y,x=pending.popleft()
        assert 0<x<w-1 and 0<y<h-1,(i,'Aperture leaked outside border')
        for yy,xx in ((y-1,x),(y+1,x),(y,x-1),(y,x+1)):
            if not mask[yy,xx] and alpha[yy,xx]==0:mask[yy,xx]=True;pending.append((yy,xx))
    spans=[]
    for y in np.flatnonzero(mask.any(axis=1)):
        xs=np.flatnonzero(mask[y]);parts=np.split(xs,np.where(np.diff(xs)>1)[0]+1)
        for part in parts:
            left,right=int(part[0]),int(part[-1])+1
            if spans and spans[-1][2:]==[left,right] and spans[-1][0]+spans[-1][1]==y:spans[-1][1]+=1
            else:spans.append([int(y),1,left,right])
    left=min(s[2] for s in spans);right=max(s[3] for s in spans)
    covered=np.zeros_like(mask)
    for y,hh,l,r in spans:covered[y:y+hh,l:r]=True
    assert np.array_equal(covered,mask),'Full health must cover exactly the aperture'
    assert not np.any(covered & (alpha>0)),'Fill must not overwrite frame artwork'
    for fraction in (0,.01,.35,.5,.99,1):
        endpoint=left+(right-left)*fraction
        widths=[max(0,min(r-l,endpoint-l)) for y,hh,l,r in spans]
        assert all(0<=width<=span[3]-span[2] for width,span in zip(widths,spans))
        if fraction==0:assert sum(widths)==0
        if fraction==1:assert sum(widths)==sum(s[3]-s[2] for s in spans)
    result.append(dict(index=i,canvas=[w,h],left=left,right=right,spans=spans))
    header.append(f'inline constexpr FSpan Spans{i}[]={{'+','.join('{'+','.join(map(str,s))+'}' for s in spans)+'};')
header.append('inline constexpr FWindow Windows[]={')
for item in result:
    i=item['index'];w,h=item['canvas']
    header.append(f'    {{{w},{h},{item["left"]},{item["right"]},Spans{i},{len(item["spans"])}}},')
header.extend(['};','}'])
(root/'Source/TheBeardAndBlade/BossHealthWindows.h').write_text('\n'.join(header)+'\n')
(root/'ArtSource/SeptemberQA/health-window-measurements.json').write_text(json.dumps(result,indent=2))
for item in result:print(item['index'],item['canvas'],'x',item['left'],item['right'],'y',item['spans'][0][0],item['spans'][-1][0]+item['spans'][-1][1])
print('HEALTH_WINDOW_VERIFY: six frames; exact aperture coverage; empty/partial/full bounds passed')
